apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nsenter-kirm7k
  name: nsenter-kirm7k
  namespace: default
spec:
  containers:
    - command:
        - nsenter
        - --target
        - "1"
#        - --mount
        - --uts
        - --ipc
        - --net
        - --pid
        - --
        - bash
        - -l
      image: nicolaka/netshoot
      name: nsenter
      resources:
        limits:
          cpu: 100m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 256Mi
      securityContext:
        privileged: true
      stdin: true
      stdinOnce: true
      tty: true
      volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access-bdrgd
          readOnly: true
  enableServiceLinks: true
  hostNetwork: true
  hostPID: true
  nodeName: minikube
  preemptionPolicy: PreemptLowerPriority
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
    - effect: NoExecute
      operator: Exists
  volumes:
    - name: kube-api-access-bdrgd
      projected:
        defaultMode: 420
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              items:
                - key: ca.crt
                  path: ca.crt
              name: kube-root-ca.crt
          - downwardAPI:
              items:
                - fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
                  path: namespace