apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  name: etcd-exporter
  labels:
    k8s-app: etcd-exporter
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: 2379
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: etcd-exporter
  labels:
    k8s-app: etcd-exporter
subsets:
- addresses:
  - ip: 192.168.0.9
    nodeName: etcd1
  - ip: 192.168.0.2
    nodeName: etcd2
  - ip: 192.168.0.6
    nodeName: etcd3
  ports:
  - name: http
    port: 2379
    protocol: TCP