version: '3'
services:
  web:
    image: registry.cn-hangzhou.aliyuncs.com/wise2c-dev/nginx-with-sub:v1
    container_name: web
    ports:
    - 8888:80
    volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d
