version: '3'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.0
    container_name: kibana
    ports:
    - 5601:5601
    volumes:
    - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
    - elasticsearch1
    - elasticsearch2
    - elasticsearch3
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    container_name: es1
    environment:
      - discovery.type=single-node
    ports:
      - 9201:9200
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    container_name: es2
    environment:
      - discovery.type=single-node
    ports:
      - 9202:9200
  elasticsearch3:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    container_name: esremote
    environment:
      - discovery.type=single-node
    ports:
      - 9203:9200
    volumes:
    - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml