apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: alicloud-disk-ssd-hangzhou-e
provisioner: diskplugin.csi.alibabacloud.com
parameters:
    zoneId: cn-hangzhou-e
    regionId: cn-hangzhou
    type: cloud_efficiency  # https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/blob/1d20480573ef4c8f64e88d5782d280245281aecd/pkg/disk/utils.go#L77
    readOnly: false
reclaimPolicy: Retain