version: '2'
services:
  java0:
    image: registry.cn-hangzhou.aliyuncs.com/wise2c-dev/tp-demo:v1
    restart: always
    environment:
      --spring.datasource.username=root
      --spring.datasource.password=root123
      --spring.datasource.url=jdbc:mysql://10.0.0.104:3306/java?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    ports:
    - 8090:8080
