version: "3.7"
services:
  proxy:
    container_name: n1
    image: nginx:mojo
    volumes:
    - type: volume
      source: db-data
      target: /data
      volume:
        nocopy: true
  proxy1:
    container_name: n2
    image: tomcat:mojo
    volumes:
    - db-data:/data
volumes:
  db-data:
