---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cassandrabackups.cassandraoperator.instaclustr.com
spec:
  additionalPrinterColumns:
  - JSONPath: .globalStatus
    description: Backup operation status
    name: Status
    type: string
  - JSONPath: .globalProgress
    description: Backup operation progress
    name: Progress
    type: string
  group: cassandraoperator.instaclustr.com
  names:
    kind: CassandraBackup
    listKind: CassandraBackupList
    plural: cassandrabackups
    singular: cassandrabackup
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        globalProgress:
          type: string
        globalStatus:
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            bandwidth:
              type: string
            cdc:
              description: Cassandra DC name to back up. Used to find the pods in
                the CDC
              type: string
            concurrentConnections:
              format: int64
              type: integer
            duration:
              type: string
            keyspaces:
              description: The list of keyspaces to back up
              items:
                type: string
              type: array
            snapshotTag:
              description: The snapshot tag for the backup
              type: string
            storageLocation:
              description: The uri for the backup target location e.g. s3 bucket,
                filepath
              type: string
            table:
              type: string
          required:
          - cdc
          - storageLocation
          - snapshotTag
          type: object
        status:
          items:
            properties:
              node:
                description: name of pod / node
                type: string
              progress:
                description: Progress shows the percentage of the operation done
                type: string
              state:
                description: State shows the status of the operation
                type: string
            required:
            - node
            - state
            - progress
            type: object
          type: array
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cassandraclusters.cassandraoperator.instaclustr.com
spec:
  group: cassandraoperator.instaclustr.com
  names:
    kind: CassandraCluster
    listKind: CassandraClusterList
    plural: cassandraclusters
    singular: cassandracluster
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          type: object
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cassandradatacenters.cassandraoperator.instaclustr.com
spec:
  group: cassandraoperator.instaclustr.com
  names:
    kind: CassandraDataCenter
    listKind: CassandraDataCenterList
    plural: cassandradatacenters
    singular: cassandradatacenter
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            backupSecretVolumeSource:
              type: object
            cassandraEnv:
              items:
                type: object
              type: array
            cassandraImage:
              type: string
            dataVolumeClaimSpec:
              type: object
            deletePVCs:
              type: boolean
            dummyVolume:
              type: object
            fsGroup:
              format: int64
              type: integer
            imagePullPolicy:
              type: string
            imagePullSecrets:
              items:
                type: object
              type: array
            nodes:
              format: int32
              type: integer
            operatorLabels:
              properties:
                nodesService:
                  additionalProperties:
                    type: string
                  type: object
                podTemplate:
                  additionalProperties:
                    type: string
                  type: object
                prometheusService:
                  additionalProperties:
                    type: string
                  type: object
                seedNodesService:
                  additionalProperties:
                    type: string
                  type: object
                statefulSet:
                  additionalProperties:
                    type: string
                  type: object
              type: object
            optimizeKernelParams:
              type: boolean
            prometheusSupport:
              type: boolean
            racks:
              items:
                properties:
                  labels:
                    additionalProperties:
                      type: string
                    type: object
                  name:
                    type: string
                required:
                - name
                - labels
                type: object
              type: array
            resources:
              type: object
            restoreFromBackup:
              type: string
            serviceAccountName:
              type: string
            sidecarEnv:
              items:
                type: object
              type: array
            sidecarImage:
              type: string
            sidecarResources:
              type: object
            userConfigMapVolumeSource:
              type: object
            userSecretVolumeSource:
              type: object
          type: object
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
---
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cassandra
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cassandra
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - cassandra
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cassandra
subjects:
  - kind: ServiceAccount
    name: cassandra
roleRef:
  kind: Role
  name: cassandra
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: cassandra
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'docker/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  'docker/default'
spec:
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
  - KILL
  - MKNOD
  - SETUID
  - SETGID
  volumes:
  - 'configMap'
  - 'emptyDir'
  - 'projected'
  - 'secret'
  - 'downwardAPI'
  - 'persistentVolumeClaim'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'MustRunAsNonRoot'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
    - min: 1
      max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
    - min: 1
      max: 65535
  readOnlyRootFilesystem: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cassandra-performance
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cassandra-performance
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - cassandra-performance
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cassandra-performance
subjects:
  - kind: ServiceAccount
    name: cassandra-performance
roleRef:
  kind: Role
  name: cassandra-performance
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: cassandra-performance
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'docker/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  'docker/default'
spec:
  privileged: true
  allowPrivilegeEscalation: true
  allowedCapabilities:
  - IPC_LOCK
  - SYS_RESOURCE
  requiredDropCapabilities:
  - KILL
  - MKNOD
  - SETUID
  - SETGID
  volumes:
  - 'configMap'
  - 'emptyDir'
  - 'projected'
  - 'secret'
  - 'downwardAPI'
  - 'persistentVolumeClaim'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
    - min: 1
      max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
    - min: 1
      max: 65535
  readOnlyRootFilesystem: false
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cassandra-operator-default-config
data:
  nodes: "3"
  cassandraImage: registry.cn-hangzhou.aliyuncs.com/mojo/cassandra:3.11.5
  sidecarImage: registry.cn-hangzhou.aliyuncs.com/mojo/cassandra-sidecar:latest
  memory: 1Gi
  disk: 1Gi
  diskMedium: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cassandra-operator
  template:
    metadata:
      labels:
        name: cassandra-operator
    spec:
      serviceAccountName: cassandra-operator
      containers:
        - name: cassandra-operator
          image: registry.cn-hangzhou.aliyuncs.com/mojo/cassandra-operator:latest
          command:
          - ./cassandra-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "cassandra-operator"
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: cassandra-operator
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'docker/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  'docker/default'
spec:
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
  - KILL
  - MKNOD
  - SETUID
  - SETGID
  volumes:
  - 'configMap'
  - 'emptyDir'
  - 'projected'
  - 'secret'
  - 'downwardAPI'
  - 'persistentVolumeClaim'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'MustRunAsNonRoot'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
    - min: 1
      max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
    - min: 1
      max: 65535
  readOnlyRootFilesystem: true
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cassandra-operator
subjects:
- kind: ServiceAccount
  name: cassandra-operator
roleRef:
  kind: Role
  name: cassandra-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: cassandra-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - services/finalizers
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - cassandra-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get
- apiGroups:
  - cassandraoperator.instaclustr.com
  resources:
  - '*'
  - cassandraclusters
  - cassandrabackups
  verbs:
  - '*'
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - use
  resourceNames:
  - cassandra-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cassandra-operator